###POST
POST http://localhost:5000/ticket
content-type: application/json

{"cliente": "Martin Ramos"
    , "Importe": "100.00"
    , "Items": 
        [
            {    "descripcion": "Coca Cola"
                //, "importe": "120.00"
            }
        ]
}

###POST
POST http://localhost:5000/ticket


###POST
POST http://localhost:5000/ticketNoFiscal

###POST
POST http://localhost:5000/ticketNoFiscal
content-type: application/json

{"cliente": "Martin Ramos"
    , "Importe": "100.00"
    , "Items": 
        [
            {    "descripcion": "Coca Cola"
                //, "importe": "120.00"
            }
        ]
}

###POST
POST http://localhost:5000/cierreX

###POST
POST http://localhost:5000/cierreZ

###POST
POST http://localhost:5000/descargarReportes

###POST
POST http://localhost:5000/testTicket